// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmxngdxrbjhwlylivzwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhteG5nZHhyYmpod2x5bGl2endvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzg3MzMsImV4cCI6MjA2MTYxNDczM30.y1-FhFif1NIH9nSCiHFHjcFr3f05ize5XenWZuPkzd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);